#include "nanoc.h"

#if defined(NANOC_DEBUG) && NANOC_DEBUG != 0

static const char *_err_msgs[] =
{
	"ERROR_UNEXPECTED_EOF",
	"ERROR_UNEXPECTED_TOKEN",
	"ERROR_EXPECTED_L_BRACE",
	"ERROR_EXPECTED_R_BRACE",
	"ERROR_EXPECTED_L_PAREN",
	"ERROR_EXPECTED_R_PAREN",
	"ERROR_EXPECTED_R_BRACKET",
	"ERROR_EXPECTED_SEMICOLON",
	"ERROR_EXPECTED_WHILE",
	"ERROR_EXPECTED_IDENTIFIER",
	"ERROR_EXPECTED_TYPE",
	"ERROR_EXPECTED_L_BRACKET",
	"ERROR_EXPECTED_INT",
	"ERROR_MISMATCHED_PAREN",
	"ERROR_DUP_MAP_ELEM",
	"ERROR_INV_VAR_DECL",
	"ERROR_INV_BREAK",
	"ERROR_INV_CONTINUE",
	"ERROR_INV_EXPR",
	"ERROR_FN_NUM_ARGS",
	"ERROR_UNDEFINED_FN",
	"ERROR_UNDEFINED_VAR",
	"ERROR_UNDEFINED_MAIN",
	"ERROR_STACK_OVERFLOW",
	"ERROR_STACK_UNDERFLOW",
	"ERROR_INV_INSTR",
	"ERROR_INV_MEM_ACCESS",
	"ERROR_INV_ESCAPE_SEQUENCE",
	"ERROR_UNTERMINATED_CHAR_LITERAL",
	"ERROR_UNEXPECTED_CHARACTER",
	"ERROR_UNTERMINATED_STRING_LITERAL"
};

const char *nanoc_error_message(i32 code)
{
	i32 idx = -code - 1;
	if(idx < 0 || idx >= (i32)ARRLEN(_err_msgs))
	{
		return "ERROR_INV_ERROR_CODE";
	}

	return _err_msgs[idx];
}

#endif
